### ISSUE TITLE
Running `db:structure:load` doesn't use token

### ISSUE THREAD

**Issue by krauseup** [haines/pg-aws_rds_iam#373]
We've been testing this gem out in our staging environment and finding it very helpful. It's been able to handle migrations and the day-to-day operation of our app just fine. We've recently tried using it for our ephemeral testing environments, and ran into an issue. In order to set up the environment, we run a `rails db:prepare` statement, so that it first tries to run migrations and, if the database doesn't exist, it goes ahead and creates the database, loads the structure.sql file, and loads seeds. The database creation works, but it runs into an error when trying to load the structure.sql file. It ends up with the error:

```
Created database 'krauseup-test'
Password for user rw_user:
psql: error: connection to server at "<RDS URL>" (<RDS IP>), port 5432 failed: fe_sendauth: no password supplied
rails aborted!
failed to execute:
psql -v ON_ERROR_STOP=1 -q -X -f /app/db/structure.sql krauseup-test
```

In our database.yaml file we're using the url field to pass the username, host, port, and database name. It looks like the `db:create` portion of `db:prepare` is using the token properly, but `db:structure:load` is trying to use a password. This may be related to https://github.com/haines/pg-aws_rds_iam/issues/290#issuecomment-1058894994, since `db:reset` also tries to load the structure file after creating the database.

**Comment by haines** [comment]
Ah, yep, this is because this gem hooks into the `pg` gem to add the token to the connection params, whereas `db:structure:load` shells out to `psql` directly. Looks like we'll need to monkey-patch [Active Record's PostgreSQL database tasks](https://github.com/rails/rails/blob/v7.0.3.1/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L103-L114) as well.

**Comment by haines** [comment]
I've pushed a new release (v0.4.1) with a fix - thanks for reporting!
