### ISSUE TITLE
IAM Role not used during deployment

### ISSUE THREAD

**Issue by benebrice** [haines/pg-aws_rds_iam#582]
I'm using Capistrano 3 to deploy my app. Configuration when well during testing but on deploy, I got this error:

```
PG::ConnectionBad: connection to server at "X.X.X.X", port 1234 failed: FATAL:  PAM authentication failed for user "my_user" (PG::ConnectionBad)
connection to server at "X.X.X.X", port 1234 failed: FATAL:  pg_hba.conf rejects connection for host "Y.Y.Y.Y", user "my_user", database "my_db"
```

It's failing on step `deploy:migrating` but when I'm running it manually with

`cap staging deploy:migrating` there is not error. I'm a bit confused.

**Comment by benebrice** [comment]
🤦🏻 Misconfiguration on my side. My bad!

**Comment by haines** [comment]
No problem, glad you got it sorted!

**Comment by benebrice** [comment]
Actually I'm still have this issue randomly.. 🤔 
But only in production. 

```ruby
ActiveRecord::NoDatabaseError
connection to server at "X.X.X.X", port 5432 failed: FATAL:  PAM authentication failed for user "my_user" (ActiveRecord::NoDatabaseError)
connection to server at "X.X.X.X", port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "X.X.X.X", user "my_user", database "my_db", no encryption
```

I did not understand the reason yet. It seems random. Do you have an idea @haines ?

**Comment by haines** [comment]
I've seen this before when the database instance is low on memory (https://github.com/haines/pg-aws_rds_iam/issues/248#issuecomment-901702886) - I would suggest checking the PostgreSQL error logs in the RDS console and maybe taking a look at your utilisation metrics?

**Comment by benebrice** [comment]
This makes sense. It's a small RDS instance. Thanks for the help @haines!
