### ISSUE TITLE
Feature request: reuse password tokens for their lifetime

### ISSUE THREAD

**Issue by matt-domsch-sp** [haines/pg-aws_rds_iam#688]
First, thank you for this work.  We'd like to use it to eliminate needing to manually manage and rotate postgres passwords when in the AWS environment.

I'm concerned that because a new password token is generated on every point of need, that we will run into the AWS 200-per-second rate limit for our production uses, which will spin up dozens of ECS instances, each with upwards of 100 connections.  This concern would be alleviated if password tokens were cached and reused until expiry.

I [submitted a PR to the ruby-pg project ](https://github.com/ged/ruby-pg/pull/605) to add fetching and caching directly there, but that maintainer rejected it as they're (unsurprisingly) not interested in having such AWS-specific code, which is also difficult to integration test, in that gem.

The key component here is the code to cache generated tokens. https://github.com/matt-domsch-sp/ruby-pg/blob/rds-iam-authentication/lib/pg/aws_iam_auth.rb

Could something similar be added to this gem to cache and reuse tokens until expiry?

**Comment by haines** [comment]
Hi @matt-domsch-sp, thanks for the feature request. This should definitely be supported; I wasn't aware of the [limitation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Limitations) before and haven't run into it myself.

I've implemented caching and token reuse in #690.

**Comment by haines** [comment]
I've released v0.7.0 which includes #690. Thanks again!

**Comment by matt-domsch-sp** [comment]
Much appreciated!  We'll put it to good use.
